# Generated by Django 5.2.9 on 2025-12-26 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата (план)')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата (факт)')),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.bookinstance', verbose_name='Экземпляр книги')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.reader', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Выдача',
                'verbose_name_plural': 'Выдачи',
            },
        ),
    ]
